name: Cross

on:
  push:
    branches:
      - main

    tags:
      - "*"
      - "**"

  pull_request:
    branches:
      - main

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cross:
    strategy:
      max-parallel: 5 #cpu cores /- runner
      fail-fast: true
      matrix:
        go-version: ["1.21.x", "1.22.x"]
        #        arch: [ x64, arm, arm64 ]
        os: [
            windows-latest,
            macos-latest,
            ubuntu-latest,
            #          macos-latest-xl, macos-13, macos-13-xl, macos-11, macos-12, macos-12-xl,
            windows-2022,
            windows-2019,
            ubuntu-20.04,
            ubuntu-22.04,
          ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          repository: darts2024/darts
          fetch-depth: 3
          submodules: false
          ref: ${{ github.ref_name == 'dev' && 'main' || github.ref_name }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          go-version-file: go.mod
          check-latest: true
          cache-dependency-path: go.sum
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -v .

      - name: Build (Race)
        run: go build -v -race .
#TODO: setup hardhat files
#    - name: Setup Env vars for hardhat
#      working-directory: hardhat
#      run: |
#        yarn
#        npm run setup

#    - name: Test Short
#      run: go test -v -race -run="^Test" -short ./...
# TODO: architecuter: https://github.com/marketplace/actions/run-on-architecture
