name: NEAR Protocol Rewards Tracking
on:
  schedule:
    - cron: "0 */12 * * *" # Every 12 hours
  workflow_dispatch: # Manual trigger
  push:
    branches: [main, "*", "**"] # Start on main branch updates

jobs:
  calculate-rewards:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Calculate Rewards
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
        run: npx near-protocol-rewards calculate       
        
      # - name: Calculate Rewards hardhat
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     GITHUB_REPO: ${{ github.repository_owner }}/hardhat
      #   run: npx near-protocol-rewards calculate    
        
      # - name: Calculate Rewards darts
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
      #     GITHUB_REPO: darts2024/darts
      #   run: npx near-protocol-rewards calculate

  
  calc-2:
      
    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          repository: darts2024/darts
          fetch-depth: 3
          # submodules: true
          # submodules: false
          ref: ${{ github.ref_name == 'dev' && 'main' || github.ref_name }}

      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Checkout all submodules
        run: |
          # ssh-keyscan github.com > ~/.ssh/known_host
          # ssh-keyscan gitlab.com >> ~/.ssh/known_host
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git config --global url."https://gitlab.com/".insteadOf "git@gitlab.com:"
          git submodule sync --recursive

          git submodule update --init --recursive
          
      - name: Caculate near
        env: 
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        run: |
          git submodule foreach --recursive '
            echo "Submodule: $name"
            remote_url=$(git config --get remote.origin.url)
            GITHUB_REPO=$(echo "$remote_url" | sed -E "s#.*[:/]([^/]+)/([^/]+)\.git#\1/\2#" | sed "s#^darts-network/#darts2024/#")
            echo "Running in submodule $GITHUB_REPO"
            export GITHUB_REPO=$GITHUB_REPO
            npx near-protocol-rewards calculate || echo "Failed in $name"
          '
      


