name: Release

on:
  push:
    # branches:
      # - main
      # - ci/**
    tags:
      - "*"
      - "**"

  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for release"
        required: true

      message:
        description: "Tag annotation"
        default: "Release: by CI"
        required: false

      branch:
        description: "Branch for release"
        default: "main"
        required: false

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  goreleaser:
    runs-on: macos-latest
    steps:
      - name: Procure the Tag
        id: procure-tag
        run: |
          tag="${{ github.event.inputs.branch || github.event.ref_name == 'dev' && 'main' || github.event.ref_name || github.ref_name == 'dev' && 'main' || github.ref_name }}"
          ref=${tag/v0.0.0-latest/main}
          ref=${ref/#v0.0.0-br-}
          # echo "ref=$ref" >> $GITHUB_ENV
          echo "ref=$ref" >> $GITHUB_OUTPUT
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "ref=$ref"
          echo "tag=$tag"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          repository: darts2024/darts
          submodules: false
          #          don't fetch tag for manual flow
          # fetch-tags: ${{ github.event_name != 'workflow_dispatch' }}
          fetch-tags: true
          fetch-depth: 100
          ref: ${{ steps.procure-tag.outputs.ref }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Git config
        run: |
          git config --global user.name Hiro
          git config --global user.email laciferin@gmail.com

      - name: Tag
        if: github.event_name == 'workflow_dispatch'
        run: |
          git tag -a ${{ github.event.inputs.tag }} -m "${{ github.event.inputs.message }}"
          echo "Tag ${{ github.event.inputs.tag }}"

      - name: Set Tag output
        id: vars
        run: |
          #echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
          git tag -a ${{steps.procure-tag.outputs.tag}} -m "ci: branch ${{steps.procure-tag.outputs.ref}}" || echo "tag exists"
          echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - uses: nowsprinting/check-version-format-action@v4
        id: version
        with:
          prefix: "v"

      - name: Version tag only step
        run: |
          echo "Found valid version format in tag!"
          echo "Full version: ${{ steps.version.outputs.full }}"
          echo "Major version: ${{ steps.version.outputs.major }}"
          echo "Major with pre-release: ${{ steps.version.outputs.major_prerelease }}"
        if: steps.version.outputs.is_valid == 'true'

      - name: Stable version only step
        run: |
          echo "Found stable version in tag!"
        if: steps.version.outputs.is_stable == 'true'

      - name: Goreleaser Args
        id: goreleaser-args
        run: |
          args=()

          if [[ "${{ steps.version.outputs.is_valid }}" == "false" && "${{steps.vars.outputs.tag}}"!="latest" ]]; then
            args+='--snapshot'
          fi

          echo "Args is $args"
          echo "args=$args" >> $GITHUB_OUTPUT

      - name: Run GoReleaser
        # continue-on-error: true
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          install-only: false

          args: |
            release --clean ${{ steps.goreleaser-args.args }}

        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: darts
          path: ./dist/*
