name: Test

on:
  push:
    branches:
      - main
      - dev
      - chore/*
      - feat/*

    tags:

  pull_request:
    branches:

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  WEB3_PUBLIC_KEY: "0x5fbb58c8b15E498442b72E2c8Dad82266ea7e135"
  SERVICE_SOLVER: "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"
  SERVICE_MEDIATORS: "0x90F79bf6EB2c4f870365E785982E1f101E93b906"
  WEB3_PRIVATE_KEY: "beb00ab9be22a34a9c940c27d1d6bfe59db9ab9de4930c968b16724907591b3f"

#  TODO: migrate to ${{secrets.SOLVER_PRIVATE_KEY}}

jobs:
  test:
    # if: false #FIXME: Disable
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          repository: darts2024/darts
          # ssh-key: |
          #   -----BEGIN OPENSSH PRIVATE KEY-----
          #   b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
          #   QyNTUxOQAAACBbvQnb/rfv0OxQLO4J++vrLJF8idsZBSspFir2j6K/bQAAAJAbMvj9GzL4
          #   /QAAAAtzc2gtZWQyNTUxOQAAACBbvQnb/rfv0OxQLO4J++vrLJF8idsZBSspFir2j6K/bQ
          #   AAAEBhoOBbyXkSmFpJyMwb0ZLWhqRND60V7q0KLMd/fcc30Fu9Cdv+t+/Q7FAs7gn76+ss
          #   kXyJ2xkFKykWKvaPor9tAAAACXB1YmxpY0tleQECAwQ=
          #   -----END OPENSSH PRIVATE KEY-----
          fetch-depth: 3
          # submodules: false
          recursive: true
          ref: ${{ github.ref_name == 'dev' && 'main' || github.ref_name }}

      - name: Investigate
        uses: lhotari/action-upterm@v1
        timeout-minutes: 360

      - name: Checkout all submodules
        run: |
          # ssh-keyscan github.com > ~/.ssh/known_host
          # ssh-keyscan gitlab.com >> ~/.ssh/known_host
          # git config --global url."https://github.com/".insteadOf "git@github.com:"
          # git config --global url."https://gitlab.com/".insteadOf "git@gitlab.com:"
          git submodule sync --recursive

          git submodule update --init --recursive

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true # This checks out all submodules
          ssh-key: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
            QyNTUxOQAAACBbvQnb/rfv0OxQLO4J++vrLJF8idsZBSspFir2j6K/bQAAAJAbMvj9GzL4
            /QAAAAtzc2gtZWQyNTUxOQAAACBbvQnb/rfv0OxQLO4J++vrLJF8idsZBSspFir2j6K/bQ
            AAAEBhoOBbyXkSmFpJyMwb0ZLWhqRND60V7q0KLMd/fcc30Fu9Cdv+t+/Q7FAs7gn76+ss
            kXyJ2xkFKykWKvaPor9tAAAACXB1YmxpY0tleQECAwQ=
            -----END OPENSSH PRIVATE KEY-----

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          check-latest: true
          cache-dependency-path: go.sum
          cache: true
          go-version-file: go.mod

      - name: Install dependencies
        run: go mod download

      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.6

      - name: Set Node.js
        continue-on-error: true
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          check-latest: true
          cache: "pnpm"
          cache-dependency-path: "hardhat/pnpm.lock"

      # - name: Source .env
      #   run: |
      #     source .env

      - name: Setup Bacalhau
        run: |
          chmod +x setup
          # install the latest bacalhau which works with GPUs (https://github.com/bacalhau-project/bacalhau/issues/2858)
          wget https://github.com/bacalhau-project/bacalhau/releases/download/v1.0.3/bacalhau_v1.0.3_linux_amd64.tar.gz
          tar xfv bacalhau_v1.0.3_linux_amd64.tar.gz
          mv bacalhau /usr/local/bin
          # configure this to where you want the ipfs data to be stored
          export BACALHAU_SERVE_IPFS_PATH=/tmp/Darts/data/ipfs
          # run bacalhau as both compute node and requester node
          ./setup bacalhau-serve &
          sleep 10

      # - name: Setup Darts Nodes- Mediator, Resource providers...
      #   run: |
      #     export ADMIN_PRIVATE_KEY=beb00ab9be22a34a9c940c27d1d6bfe59db9ab9de4930c968b16724907591b3f
      #     export FAUCET_ADDRESS=0x5fbb58c8b15E498442b72E2c8Dad82266ea7e135
      #     export FAUCET_PRIVATE_KEY=beb00ab9be22a34a9c940c27d1d6bfe59db9ab9de4930c968b16724907591b3f
      #     export SOLVER_ADDRESS=0x5fbb58c8b15E498442b72E2c8Dad82266ea7e135
      #     export SOLVER_PRIVATE_KEY=beb00ab9be22a34a9c940c27d1d6bfe59db9ab9de4930c968b16724907591b3f
      #     export MEDIATOR_ADDRESS=0x5fbb58c8b15E498442b72E2c8Dad82266ea7e135
      #     export MEDIATOR_PRIVATE_KEY=beb00ab9be22a34a9c940c27d1d6bfe59db9ab9de4930c968b16724907591b3f
      #     export RESOURCE_PROVIDER_ADDRESS=0x5fbb58c8b15E498442b72E2c8Dad82266ea7e135
      #     export RESOURCE_PROVIDER_PRIVATE_KEY=beb00ab9be22a34a9c940c27d1d6bfe59db9ab9de4930c968b16724907591b3f
      #     export JOB_CREATOR_ADDRESS=0x5fbb58c8b15E498442b72E2c8Dad82266ea7e135
      #     export JOB_CREATOR_PRIVATE_KEY=beb00ab9be22a34a9c940c27d1d6bfe59db9ab9de4930c968b16724907591b3f
      #     export DIRECTORY_ADDRESS=0x5fbb58c8b15E498442b72E2c8Dad82266ea7e135
      #     export DIRECTORY_PRIVATE_KEY=beb00ab9be22a34a9c940c27d1d6bfe59db9ab9de4930c968b16724907591b3f

      #     export INFURA_KEY=cd97920f485a4ed0b1f7f4bfb447b1dc
      #     export LOG_LEVEL=info
      #     export NETWORK=geth
      #     export NETWORK=sepolia

      #     export WEB3_RPC_URL=wss://sepolia.infura.io/ws/v3/cd97920f485a4ed0b1f7f4bfb447b1dc
      #     export WEB3_CHAIN_ID=11155111

      #     ./setup balances
      #     ./setup compile-contracts
      #     ./setup deploy-contracts

      #     ./setup solver
      #     sleep 10
      #     ./setup mediator

      - name: Setup Clean
        run: |
          ./setup boot

      - name: Test Short
        run: go test -v -run="^Test" -short ./... -timeout 20m

      - name: Test
        run: go test -v -run="^Test" ./... -timeout 6h
